### ISSUE TITLE
Usage of span

### ISSUE THREAD

**Issue by asadmehdi785** [aschera/tea-cozy#1]
https://github.com/aschera/tea-cozy/blob/5ca10b01628c73f1773cfed65a8d7b4905bc5e02/index.html#L43-L51

For this part, it may be better to just use a `p` tag for the text, rather than putting each word within a `span` tag. In general, we want to use `span` to give specific styling to a part of some text. However, in this case it's not really necessary, so we can use `p` instead.

**Comment by aschera** [comment]
Hello, Yes you are right. I was experimenting with having them as flex items - and the  h4 being a flex container. I understand that its silly like this. Thanks for your comment.
